baseurl = "http://worldping.raintank.io/"
languageCode = "en-us"
title = "raintank"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  section = "section"

[[menu.main]]
    name = "about worldPing"
    weight = -110
    identifier = "worldPing"
    url = "#"

[[menu.main]]
    name = "what is worldPing?"
    weight = -110
    identifier = "what"
    url = "/worldping/"
    parent = "worldPing"

[[menu.main]]
    name = "use cases"
    weight = -100    
    identifier = "usecases"
    url = "/worldping/use-cases"
    parent = "worldPing"

[[menu.main]]
    name = "road map"
    weight = -80    
    identifier = "roadmap"
    url = "/worldping/road-map/"
    parent = "worldPing"

[[menu.main]]
    name = "faq"
    weight = -60
    indentifier = "faq"
    url = "/worldping/faq"
    parent = "worldPing"

[[menu.main]]
    name = "pricing"
    weight = -50
    identifier = "pricing"
    url = "/pricing/"   

[[menu.main]]
    name = "docs"
    weight = -40
    identifier = "docs"
    url = "/docs/"    
